-- Create roadmap_steps table
create table public.roadmap_steps (
  id bigint generated by default as identity primary key,
  num integer not null,
  title text not null,
  description text not null,
  icon_name text not null,
  bg_icon text not null,
  text_icon text not null,
  shadow_icon text not null,
  border_card text not null,
  text_title text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert default roadmap data
insert into public.roadmap_steps (num, title, description, icon_name, bg_icon, text_icon, shadow_icon, border_card, text_title) values
(1, 'Online Orientation Meeting', 'Attend the introductory Google Meet session where internship guidelines, project workflow, and expectations will be explained.', 'CalendarDays', 'bg-blue-600', 'text-blue-600', 'shadow-[0_0_20px_rgba(37,99,235,0.6)]', 'hover:border-blue-400', 'text-blue-900'),
(2, 'Learning Resources Shared', 'Access curated open-source learning materials, documentation, tutorials, and reference resources provided by DAKH Edu Solutions.', 'BookOpen', 'bg-green-600', 'text-green-600', 'shadow-[0_0_20px_rgba(22,163,74,0.6)]', 'hover:border-green-400', 'text-green-900'),
(3, 'Mentor Assignment', 'A dedicated mentor will be assigned to guide you throughout the internship and support your learning journey.', 'UserCheck', 'bg-orange-600', 'text-orange-600', 'shadow-[0_0_20px_rgba(234,88,12,0.6)]', 'hover:border-orange-400', 'text-orange-900'),
(4, 'Project Briefing', 'A simple domain-based project will be assigned along with clear objectives, requirements, and submission guidelines.', 'Lightbulb', 'bg-purple-600', 'text-purple-600', 'shadow-[0_0_20px_rgba(147,51,234,0.6)]', 'hover:border-purple-400', 'text-purple-900'),
(5, 'Project Development', 'Learn from the provided resources and complete the assigned project within the internship duration.', 'Code2', 'bg-yellow-500', 'text-yellow-600', 'shadow-[0_0_20px_rgba(234,179,8,0.6)]', 'hover:border-yellow-400', 'text-yellow-700'),
(6, 'Project Submission & Review', 'Submit your completed project to your assigned mentor for evaluation and feedback.', 'Send', 'bg-cyan-600', 'text-cyan-600', 'shadow-[0_0_20px_rgba(8,145,178,0.6)]', 'hover:border-cyan-400', 'text-cyan-900');

-- Enable RLS for roadmap_steps
alter table public.roadmap_steps enable row level security;
create policy "Allow public read access to roadmap_steps" on public.roadmap_steps for select using (true);
create policy "Allow authenticated insert/update on roadmap_steps" on public.roadmap_steps for all using (auth.role() = 'authenticated');

-- Create registrations table
create table public.registrations (
  id uuid default gen_random_uuid() primary key,
  full_name text not null,
  email text not null,
  phone text not null,
  college text not null,
  department text not null,
  year_of_study text not null,
  domain text not null,
  plan_name text not null,
  plan_price text not null,
  referral_code text,
  utr_number text not null,
  payment_completed boolean default false,
  status text default 'Pending',
  intern_number text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for registrations
alter table public.registrations enable row level security;
create policy "Allow public insert access to registrations" on public.registrations for insert with check (true);
create policy "Allow authenticated read/write access to registrations" on public.registrations for all using (auth.role() = 'authenticated');
