-- Create roadmap_steps table
create table public.roadmap_steps (
  id bigint generated by default as identity primary key,
  num integer not null,
  title text not null,
  description text not null,
  icon_name text not null,
  bg_icon text not null,
  text_icon text not null,
  shadow_icon text not null,
  border_card text not null,
  text_title text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert default roadmap data
insert into public.roadmap_steps (num, title, description, icon_name, bg_icon, text_icon, shadow_icon, border_card, text_title) values
(1, 'Online Orientation Meeting', 'Attend the introductory Google Meet session where internship guidelines, project workflow, and expectations will be explained.', 'CalendarDays', 'bg-blue-600', 'text-blue-600', 'shadow-[0_0_20px_rgba(37,99,235,0.6)]', 'hover:border-blue-400', 'text-blue-900'),
(2, 'Learning Resources Shared', 'Access curated open-source learning materials, documentation, tutorials, and reference resources provided by DAKH Edu Solutions.', 'BookOpen', 'bg-green-600', 'text-green-600', 'shadow-[0_0_20px_rgba(22,163,74,0.6)]', 'hover:border-green-400', 'text-green-900'),
(3, 'Mentor Assignment', 'A dedicated mentor will be assigned to guide you throughout the internship and support your learning journey.', 'UserCheck', 'bg-orange-600', 'text-orange-600', 'shadow-[0_0_20px_rgba(234,88,12,0.6)]', 'hover:border-orange-400', 'text-orange-900'),
(4, 'Project Briefing', 'A simple domain-based project will be assigned along with clear objectives, requirements, and submission guidelines.', 'Lightbulb', 'bg-purple-600', 'text-purple-600', 'shadow-[0_0_20px_rgba(147,51,234,0.6)]', 'hover:border-purple-400', 'text-purple-900'),
(5, 'Project Development', 'Learn from the provided resources and complete the assigned project within the internship duration.', 'Code2', 'bg-yellow-500', 'text-yellow-600', 'shadow-[0_0_20px_rgba(234,179,8,0.6)]', 'hover:border-yellow-400', 'text-yellow-700'),
(6, 'Project Submission & Review', 'Submit your completed project to your assigned mentor for evaluation and feedback.', 'Send', 'bg-cyan-600', 'text-cyan-600', 'shadow-[0_0_20px_rgba(8,145,178,0.6)]', 'hover:border-cyan-400', 'text-cyan-900');

-- Enable RLS for roadmap_steps
alter table public.roadmap_steps enable row level security;
create policy "Allow public read access to roadmap_steps" on public.roadmap_steps for select using (true);
create policy "Allow authenticated insert/update on roadmap_steps" on public.roadmap_steps for all using (auth.role() = 'authenticated');

-- Create registrations table
create table public.registrations (
  id uuid default gen_random_uuid() primary key,
  full_name text not null,
  email text not null,
  phone text not null,
  college text not null,
  department text not null,
  year_of_study text not null,
  domain text not null,
  plan_name text not null,
  plan_price text not null,
  referral_code text,
  utr_number text not null,
  payment_completed boolean default false,
  status text default 'Pending',
  intern_number text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for registrations
alter table public.registrations enable row level security;
create policy "Allow public insert access to registrations" on public.registrations for insert with check (true);
create policy "Allow authenticated read/write access to registrations" on public.registrations for all using (auth.role() = 'authenticated');

-- Create blogs table
create table public.blogs (
  id uuid default gen_random_uuid() primary key,
-- Create roadmap_steps table
create table public.roadmap_steps (
  id bigint generated by default as identity primary key,
  num integer not null,
  title text not null,
  description text not null,
  icon_name text not null,
  bg_icon text not null,
  text_icon text not null,
  shadow_icon text not null,
  border_card text not null,
  text_title text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert default roadmap data
insert into public.roadmap_steps (num, title, description, icon_name, bg_icon, text_icon, shadow_icon, border_card, text_title) values
(1, 'Online Orientation Meeting', 'Attend the introductory Google Meet session where internship guidelines, project workflow, and expectations will be explained.', 'CalendarDays', 'bg-blue-600', 'text-blue-600', 'shadow-[0_0_20px_rgba(37,99,235,0.6)]', 'hover:border-blue-400', 'text-blue-900'),
(2, 'Learning Resources Shared', 'Access curated open-source learning materials, documentation, tutorials, and reference resources provided by DAKH Edu Solutions.', 'BookOpen', 'bg-green-600', 'text-green-600', 'shadow-[0_0_20px_rgba(22,163,74,0.6)]', 'hover:border-green-400', 'text-green-900'),
(3, 'Mentor Assignment', 'A dedicated mentor will be assigned to guide you throughout the internship and support your learning journey.', 'UserCheck', 'bg-orange-600', 'text-orange-600', 'shadow-[0_0_20px_rgba(234,88,12,0.6)]', 'hover:border-orange-400', 'text-orange-900'),
(4, 'Project Briefing', 'A simple domain-based project will be assigned along with clear objectives, requirements, and submission guidelines.', 'Lightbulb', 'bg-purple-600', 'text-purple-600', 'shadow-[0_0_20px_rgba(147,51,234,0.6)]', 'hover:border-purple-400', 'text-purple-900'),
(5, 'Project Development', 'Learn from the provided resources and complete the assigned project within the internship duration.', 'Code2', 'bg-yellow-500', 'text-yellow-600', 'shadow-[0_0_20px_rgba(234,179,8,0.6)]', 'hover:border-yellow-400', 'text-yellow-700'),
(6, 'Project Submission & Review', 'Submit your completed project to your assigned mentor for evaluation and feedback.', 'Send', 'bg-cyan-600', 'text-cyan-600', 'shadow-[0_0_20px_rgba(8,145,178,0.6)]', 'hover:border-cyan-400', 'text-cyan-900');

-- Enable RLS for roadmap_steps
alter table public.roadmap_steps enable row level security;
create policy "Allow public read access to roadmap_steps" on public.roadmap_steps for select using (true);
create policy "Allow authenticated insert/update on roadmap_steps" on public.roadmap_steps for all using (auth.role() = 'authenticated');

-- Create registrations table
create table public.registrations (
  id uuid default gen_random_uuid() primary key,
  full_name text not null,
  email text not null,
  phone text not null,
  college text not null,
  department text not null,
  year_of_study text not null,
  domain text not null,
  plan_name text not null,
  plan_price text not null,
  referral_code text,
  utr_number text not null,
  payment_completed boolean default false,
  status text default 'Pending',
  intern_number text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for registrations
alter table public.registrations enable row level security;
create policy "Allow public insert access to registrations" on public.registrations for insert with check (true);
create policy "Allow authenticated read/write access to registrations" on public.registrations for all using (auth.role() = 'authenticated');

-- Create blogs table
create table public.blogs (
  id uuid default gen_random_uuid() primary key,
  author_name text not null,
  title text not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for blogs
alter table public.blogs enable row level security;
create policy "Allow public insert access to blogs" on public.blogs for insert with check (true);
create policy "Allow public read access to blogs" on public.blogs for select using (true);
create policy "Allow authenticated delete on blogs" on public.blogs for delete using (auth.role() = 'authenticated');

-- Create events table
create table public.events (
  id uuid default gen_random_uuid() primary key,
  title text,
  image_url text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for events
alter table public.events enable row level security;
create policy "Allow public read access to events" on public.events for select using (true);
create policy "Allow authenticated insert/update on events" on public.events for all using (auth.role() = 'authenticated');

-- Create freelancer_applications table
create table public.freelancer_applications (
  id uuid default gen_random_uuid() primary key,
  full_name text not null,
  email text not null,
  phone text not null,
  city text,
  college_name text not null,
  year_of_study text not null,
  department text not null,
  skills text[] not null,
  experience_level text not null,
  portfolio_url text,
  linkedin_url text,
  github_url text,
  availability text not null,
  bio text not null,
  why_dakh text not null,
  status text default 'pending',
  applied_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for freelancer_applications
alter table public.freelancer_applications enable row level security;
create policy "Allow public insert access to freelancer_applications" on public.freelancer_applications for insert with check (true);
create policy "Allow authenticated read/write access to freelancer_applications" on public.freelancer_applications for all using (auth.role() = 'authenticated');

-- Create products table
create table public.products (
  id uuid default gen_random_uuid() primary key,
  title text not null,
  image_url text not null,
  description text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for products
alter table public.products enable row level security;
create policy "Allow public read access to products" on public.products for select using (true);
create policy "Allow authenticated insert/update on products" on public.products for all using (auth.role() = 'authenticated');
 
 - -   C r e a t e   a d v e r t i s e m e n t s   t a b l e  
 c r e a t e   t a b l e   p u b l i c . a d v e r t i s e m e n t s   (  
     i d   u u i d   d e f a u l t   g e n _ r a n d o m _ u u i d ( )   p r i m a r y   k e y ,  
     i m a g e _ u r l   t e x t   n o t   n u l l ,  
     l i n k _ u r l   t e x t ,  
     c r e a t e d _ a t   t i m e s t a m p   w i t h   t i m e   z o n e   d e f a u l t   t i m e z o n e ( ' u t c ' : : t e x t ,   n o w ( ) )   n o t   n u l l  
 ) ;  
 a l t e r   t a b l e   p u b l i c . a d v e r t i s e m e n t s   e n a b l e   r o w   l e v e l   s e c u r i t y ;  
 c r e a t e   p o l i c y   \  
 A l l o w  
 p u b l i c  
 r e a d  
 a c c e s s  
 t o  
 a d v e r t i s e m e n t s \   o n   p u b l i c . a d v e r t i s e m e n t s   f o r   s e l e c t   u s i n g   ( t r u e ) ;  
 c r e a t e   p o l i c y   \  
 A l l o w  
 a u t h e n t i c a t e d  
 i n s e r t / u p d a t e  
 o n  
 a d v e r t i s e m e n t s \   o n   p u b l i c . a d v e r t i s e m e n t s   f o r   a l l   u s i n g   ( a u t h . r o l e ( )   =   ' a u t h e n t i c a t e d ' ) ;  
 